version: '3.7'
services:
  app1:
    # build: api
    # ports:
    #   - 3011:3011
    image: nodeapp
    depends_on:
      - mongo
    environment:
      PORT: 3011
      DB_USERNAME: mongouser
      DB_PASSWORD: mongopassword
      DB_URL: mongo:27017/school
    expose:
      - "3011"
    networks:
      - app
  app2:
    image: nodeapp
    depends_on:
      - mongo
    environment:
      PORT: 3012
      DB_USERNAME: mongouser
      DB_PASSWORD: mongopassword
      DB_URL: mongo:27017/school
    expose:
      - "3012"
    networks:
      - app
  app3:
    image: nodeapp
    depends_on:
      - mongo
    environment:
      PORT: 3013
      DB_USERNAME: mongouser
      DB_PASSWORD: mongopassword
      DB_URL: mongo:27017/school
    expose:
      - "3013"
    networks:
      - app
  mongo:
    image: mongo:latest
    restart: always
    volumes:
      - mongo:/data/db
      - ./app/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - app
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx:/etc/nginx/templates
    networks:
      - app
networks:
  app:
    driver: bridge
volumes:
  mongo: